config/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from config.views import robots_txt
from seed.api.base.urls import urlpatterns as api
from seed.landing.views import (
    password_reset_complete,
    password_reset_confirm,
    password_reset_done
)
from seed.views.main import angular_js_tests, health_check, version

schema_view = get_schema_view(
    openapi.Info(
        title="SEED API",
        default_version='v3',
        description="SEED Platform API Documentation",
        # terms_of_service="https://www.google.com/policies/terms/",
        # contact=openapi.Contact(email="contact@snippets.local"),
        # license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=(permissions.AllowAny,),
)


def trigger_error(request):
    """Endpoint for testing sentry with a divide by zero"""
    1 / 0


urlpatterns = [
    re_path(r'^accounts/password/reset/done/$', password_reset_done, name='password_reset_done'),
    re_path(
        r'^accounts/password/reset/complete/$',
        password_reset_complete,
        name='password_reset_complete',
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        password_reset_confirm,
        name='password_reset_confirm'
    ),

    # Application
    re_path(r'^', include(('seed.landing.urls', "seed.landing"), namespace="landing")),
    re_path(r'^app/', include(('seed.urls', "seed"), namespace="seed")),
    re_path(r'^documentation/', include(('seed.docs.urls', 'seed.docs'), namespace='docs')),

    # root configuration items
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^robots\.txt', robots_txt, name='robots_txt'),

    # API
    re_path(r'^api/health_check/$', health_check, name='health_check'),
    re_path(r'^api/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^api/version/$', version, name='version'),
    re_path(r'^api/', include((api, "seed"), namespace='api')),
    re_path(r'^oauth/', include(('oauth2_jwt_provider.urls', 'oauth2_jwt_provider'), namespace='oauth2_provider')),

    # test sentry error
    path('sentry-debug/', trigger_error)
]

handler404 = 'seed.views.main.error404'
handler410 = 'seed.views.main.error410'
handler500 = 'seed.views.main.error500'


if settings.DEBUG:
    from django.contrib import admin

    admin.autodiscover()
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # test URLs
        re_path(r'^angular_js_tests/$', angular_js_tests, name='angular_js_tests'),

        # admin
        re_path(r'^admin/', admin.site.urls),
    ]

seed/api/base/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.urls import include, re_path

from seed.api.v3.urls import urlpatterns as api_v3
from seed.views.main import error410

deprecated_apis = [
    re_path(r'^v1/', error410, name='v1'),
    re_path(r'^v2/', error410, name='v2'),
    re_path(r'^v2\.1/', error410, name='v2.1'),
]

urlpatterns = deprecated_apis + [
    re_path(r'^v3/', include((api_v3, 'seed'), namespace='v3')),
]

seed/landing/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.conf import settings
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordChangeView,
    logout_then_login
)
from django.urls import re_path

from seed.landing.views import (
    account_activation_sent,
    activate,
    create_account,
    landing_page,
    password_reset,
    password_reset_complete,
    password_reset_done,
    signup
)

urlpatterns = [
    re_path(r'^$', landing_page, name='landing_page'),
    re_path(r'^accounts/login/$', landing_page, name='login'),
    re_path(
        r'^accounts/logout/$',
        logout_then_login,
        name='logout'
    ),
    re_path(r'^accounts/password/reset/$', password_reset, name='password_reset'),
    re_path(r'^accounts/password/reset/done/$', password_reset_done, name='password_reset_done'),
    re_path(
        r'^accounts/password/reset/complete/$',
        password_reset_complete,
        name='password_reset_complete',
    ),
    re_path(
        (
            r'^accounts/setup/(?P<uidb64>[0-9A-Za-z_\-]+)/'
            '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$'
        ),
        signup,
        name='signup'
    ),
    re_path(
        r'^password_change/$',
        PasswordChangeView.as_view(),
        {'template_name': 'landing/password_change_form.html'},
        name="password_change"
    ),
    re_path(
        r'^password_change/done/$',
        PasswordChangeDoneView.as_view(),
        {'template_name': 'landing/password_change_done.html'}
    ),
]

if settings.INCLUDE_ACCT_REG:
    urlpatterns += [
        re_path(r'^accounts/create/$', create_account, name='create_account'),
        re_path(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
        re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate')
    ]

seed/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.urls import re_path

from seed.views.main import home

urlpatterns = [
    re_path(r'^$', home, name='home'),
]

seed/landing/models.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
import base64
import hmac
import re
import uuid

from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    UserManager
)
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import gettext_lazy as _
from rest_framework import exceptions

from seed.lib.superperms.orgs.models import Organization

# sha1 used for api_key creation, but may vary by python version
try:
    from hashlib import sha1
except ImportError:
    import sha
    sha1 = sha.sha


class SEEDUser(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username, password and email are required. Other fields are optional.
    """
    username = models.EmailField(
        _('username (email)'), unique=True,
        help_text=_('User\'s email address.  Used for auth as well.'))
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(
        _('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    default_custom_columns = models.JSONField(default=dict)
    default_building_detail_custom_columns = models.JSONField(default=dict)
    show_shared_buildings = models.BooleanField(
        _('active'), default=False,
        help_text=_('shows shared buildings within search results'))
    default_organization = models.ForeignKey(
        Organization,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='default_users'
    )
    api_key = models.CharField(
        _('api key'),
        max_length=128,
        blank=True,
        default='',
        db_index=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    @classmethod
    def process_header_request(cls, request):
        """
        Process the header string to return the user if it is a valid user.

        :param request: object, request object with HTTP Authorization
        :return: User object
        """
        auth_header = request.META.get('Authorization')

        if not auth_header:
            auth_header = request.META.get('HTTP_AUTHORIZATION')

        if not auth_header:
            return None

        if not auth_header.startswith('Bearer') or not getattr(request, 'user', None):
            try:
                if not auth_header.startswith('Basic'):
                    raise exceptions.AuthenticationFailed('Only Basic HTTP_AUTHORIZATION is supported')

                auth_header = auth_header.split()[1]
                auth_header = base64.urlsafe_b64decode(auth_header).decode('utf-8')
                username, api_key = auth_header.split(':')

                valid_api_key = re.search('^[a-f0-9]{40}$', api_key)
                if not valid_api_key:
                    raise exceptions.AuthenticationFailed('Invalid API key')

                user = SEEDUser.objects.get(api_key=api_key, username=username)
                return user
            except ValueError:
                raise exceptions.AuthenticationFailed('Invalid HTTP_AUTHORIZATION Header')
            except SEEDUser.DoesNotExist:
                raise exceptions.AuthenticationFailed('Invalid API key')

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.username)

    def deactivate_user(self):
        self.is_active = False
        self.save()

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])

    def generate_key(self):
        """
        Creates and sets an API key for this user.
        Adapted from tastypie:

        https://github.com/toastdriven/django-tastypie/blob/master/tastypie/models.py#L47
        """
        new_uuid = uuid.uuid4()
        api_key = hmac.new(new_uuid.bytes, digestmod=sha1).hexdigest()
        self.api_key = api_key
        self.save()

    def save(self, *args, **kwargs):
        """
        Ensure that email and username are synced.
        """

        # NL: Why are we setting the email to the user name, don't we need the
        # email? It seems that the username is then suppose to be the email,
        # correct? Regardless, this code seems problematic
        if self.email.lower() != self.username:
            self.email = self.username
        return super().save(*args, **kwargs)

seed/landing/forms.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from seed.landing.models import SEEDUser


class LoginForm(forms.Form):
    email = forms.EmailField(
        label=_("Email"),
        help_text=_("ex: joe@company.com"),
        widget=forms.TextInput(
            attrs={'class': 'field', 'placeholder': _('Email Address')}
        )
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(
            attrs={'class': 'field', 'placeholder': _('Password'), 'autocomplete': 'off'}
        ),
        required=True
    )


class CustomCreateUserForm(UserCreationForm):
    class Meta:
        model = SEEDUser
        fields = ['username']
        widgets = {
            'username': forms.fields.EmailInput(attrs={'placeholder': 'Email Address'})
        }

    def __init__(self, *args, **kwargs):
        super(CustomCreateUserForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'class': 'field', 'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'class': 'field', 'placeholder': 'Confirm Password'})

seed/landing/templates/landing/account_activation_invalid.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}

{% block content %}
  <div class="page login">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}
      <!-- END .section_marketing -->
      <div class="section_forms">
        <div class="form_title">
          <h2>{% trans "Thank you" %}</h2>

          <div class="signup_form">
            <p>{% trans "This email link is invalid." %}<br></p>
            <div>
              <a href="{% url "landing:landing_page" %}" type="submit" class="btn">{% trans "Back to Home" %}</a>
            </div>
          </div>
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->
  </div>
  <!-- END .page -->
{% endblock %}

seed/landing/templates/landing/create_account.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}{% load settings_value %}
{% block js %}{{ block.super }}
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <script type="text/javascript">

    $(document).ready(function() {
      $('#id_new_password1').focus();
      $('#id_new_password1').attr('placeholder', '{% trans "Password" %}');
      $('#id_new_password2').attr('placeholder', '{% trans "Password again" %}');

    });
  </script>
{% endblock %}
{% block content %}
  <div class="page login">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}
      <!-- END .section_marketing -->
      <div class="section_forms">
        <div class="form_title">
          <h2>{% trans "Create Your Account" %}</h2>
          <p>By creating an account, signing in, and using this website, you are agreeing to our <a href="{{ STATIC_URL }}seed/Terms_of_Service.txt" target="_blank" rel="noopener noreferrer">Terms of
            Service</a>.</p>
          <form id="AuthNewPassword" class="signup_form" action="" method="post">
            {% csrf_token %}
            <table class="signup_table">
              {{ form.as_table }}
            </table>
            {% include "landing/_password_note.html" %}
            <div style="padding-left: 4.5em" class="g-recaptcha" data-sitekey="{% settings_value "GOOGLE_RECAPTCHA_SITE_KEY" %}"></div>
            <div style="padding-bottom: 2em">
              <input class="btn btn-primary" type="submit"
                     value="{% block password_submit %}{% trans "Create my account" %}{% endblock %}">
              <a href="{% url "landing:landing_page" %}" type="submit"
                 class="btn btn-cancel btn-default">{% trans "Cancel" %}</a>
            </div>
          </form>
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->
  </div>
  <!-- END .page -->
{% endblock %}

seed/landing/templates/landing/home.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}

{% block content %}
  <div class="page">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}

      <div class="section_forms">
        <div class="clearfix"></div>
        <div class="form_title">
          <h2>{% trans "Log in to SEED Platform™" %}</h2>
          {% if 'setup_complete' in request.GET %}
            <p>{% trans "Thank you for creating your account! Please sign in below." %}
          {% endif %}
          {% if 'logout' in request.GET %}
            <p>{% trans "You have successfully logged out. You may log in again below." %}</p>
          {% endif %}
          <form action="{% url "landing:login" %}?next={% url "seed:home" %}" method="POST" class="signup_form" autocomplete="off">{% csrf_token %}
            <table class="signup_table">
              {{ login_form.as_table }}
            </table>
            <div class="terms-link">
              <p>{% trans "By clicking the Log In button you accept the NREL Data Terms." %} <a onclick="toggleTerms()">{% trans "View/Hide Terms" %}</a></p>
            </div>

            <div id="terms-and-conditions">
              <h3>DOE Standard Energy Efficiency Data Platform | NREL Data Terms</h3>

              <p>You, and your company or organization (the PROVIDER) have agreed to upload and provide PROPRIETARY DATA, including energy efficiency data, building data, and building energy
                performance data to the Standard Energy Efficiency Data (SEED™) Platform database that the U.S. Department of Energy (the Government) and Alliance for Sustainable Energy, LLC
                (“Alliance”) the manager and operator of the National Renewable Energy Laboratory (“NREL”) (the RECIPIENT) have created and provide for use for registered users.</p>

              <p>PROPRIETARY DATA is defined as follows:</p>
              <p>(a) information that embody trade secrets or commercial or financial information that is confidential and privileged; (b) information that is confidential and privileged and developed
                at private expense (i.e., not with Federal funds); (c) information that is not customarily released to the public; and/or (d) information whose disclosure to the public could result in
                financial harm to the PROVIDER, to owners of buildings whose information is contained in the PROPRIETARY DATA, or to other stakeholders.</p>
              <p>In order to upload PROPRIETARY DATA, you will be required to create an account and provide the RECIPIENT with a username, password, and email address. You are solely responsible for
                maintaining the confidentiality of the password and username you provided during the registration process and are fully responsible for all activities that occur under your password or
                account.</p>
              <p>The PROPRIETARY DATA shall remain protected until the PROVIDER provides notice of termination of their account on the SEED Platform and provides notice to remove PROPRIETARY DATA from
                the SEED Platform database, at which time the RECIPIENT will promptly return and/or destroy the PROPRIETARY DATA uploaded in the SEED Platform database.</p>
              <p>By providing the PROPRIETARY DATA, PROVIDER agrees to the following:</p>
              <ol>
                <li>PROVIDER has the authority to provide the PROPRIETARY DATA to the RECIPIENT, that the information provided constitutes PROPRIETARY DATA, and consents to the information provided
                  being labeled and treated as PROPRIETARY DATA. If PROVIDER wishes to provide non-proprietary data, please contact <a href="mailto:BTODataTools@ee.doe.gov">BTODataTools@ee.doe.gov</a>.
                </li>
                <li>RECIPIENT may host, display, and manage such PROPRIETARY DATA for the PROVIDER and the Government to access, analyze, and manage through the SEED Platform.</li>
                <li>RECIPIENT may use, view, or duplicate the PROPRIETARY DATA and may share the PROPRIETARY DATA with support services contractors within the scope of their contracts. RECIPIENT may
                  share the PROPRIETARY DATA to other DOE National Laboratories participating in the SEED Platform project, under the restriction that (i) the PROPRIETARY DATA be retained in
                  confidence and not be further disclosed, (ii) the PROPRIETARY DATA will be destroyed when the DOE National Laboratory’s participation in the SEED Platform has ended.
                </li>
              </ol>
            </div>

            <input type="submit" class="btn btn-primary" value="{% trans "Log In" %}"><br>
            <div>
              {% if context.self_registration %}
                <a class="create_account" href="{% url "landing:create_account" %}">{% trans "Create my Account" %}</a>
              {% endif %}
              <a class="forgot_password" href="{% url "landing:password_reset" %}">{% trans "Forgot password?" %}</a>
            </div>
          </form>
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->

  </div>
  <!-- END .page -->
{% endblock %}
{% block js %}
  <script>
    function toggleTerms () {
      const terms = document.getElementById('terms-and-conditions');
      const hidden = ['', 'none'].includes(terms.style.display);
      terms.style.display = hidden ? 'block' : 'none';
    }
  </script>
{% endblock %}

seed/landing/templates/landing/password_reset.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}

{% block content %}
  <div class="page login">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}
      <!-- END .section_marketing -->
      <div class="section_forms">
        <div class="form_title">
          <h2>Password Reset</h2>

          <form id="form-password-reset" class="signup_form" action="" method="post">
            <table class="signup_table">
              <tr>
                <td>
                  <p>Forgot your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
                </td>
              </tr>
              <tr>
                <td>
                  {% csrf_token %}
                  {% if form.email.errors %}
                    <div class="form-error">
                      {% firstof form.email.errors %}
                    </div>
                  {% endif %}
                </td>
              </tr>

              <tr>
                <th>
                  <label for="id_email">Email address:</label>
                </th>
                <td>
                  <input id="id-email" type="text" placeholder="Email Address" name="email" class="field">
                </td>
              </tr>
            </table>
            <div>
              <input style="float: none;" class="btn btn-primary" type="submit" value="Reset my password">
              <a href="{% url "landing:login" %}" type="submit" class="btn btn-default">Cancel</a>
            </div>
          </form>
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->
  </div>
  <!-- END .page -->
{% endblock %}

seed/landing/templates/landing/password_reset_complete.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}

{% block content %}
  <div class="page login">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}
      <!-- END .section_marketing -->
      <div class="section_forms">
        <div class="form_title">
          <h2>Password Set</h2>
          <div class="signup_form">
            <p>Your password has been set.</p>
            <div>
              <a href="{% url "landing:login" %}" type="submit" class="btn btn-primary">Back to Login</a>
            </div>
          </div>
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->
  </div>
  <!-- END .page -->
{% endblock %}

seed/landing/templates/landing/password_reset_confirm.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}


{% block js %}{{ block.super }}
  <script type="text/javascript">

    $(document).ready(function() {
      $('#id_new_password1').focus();
      $('#id_new_password1').attr('placeholder', '{% trans "Password" %}');
      $('#id_new_password2').attr('placeholder', '{% trans "Password again" %}');

    });

  </script>
{% endblock %}


{% block content %}

  <div class="page login">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}
      <!-- END .section_marketing -->
      <div class="section_forms">
        <div class="form_title">
          <h2>{% trans "Change Your Password" %}</h2>

          <form id="AuthNewPassword" class="signup_form" action="" method="post">
            {% csrf_token %}
            <table class="signup_table">
              <tr>
                {% if validlink %}
                  <td>
                    <p>{% block password_set_instructions %}{% trans "To change your password, enter your requested password twice." %}{% endblock %}</p>
                  </td>
                {% else %}
                  <td>
                    <p>{% trans "The password link was invalid, possibly because it has already been used.  Please request a new password reset." %}
                      <a href="{% url "landing:password_reset" %}">{% trans "Password reset" %}</a></p>
                  </td>
                {% endif %}
              </tr>

              {% if validlink %}
                <tr>
                  <th>
                    <label for="id_new_password1">{% trans "New password" %}</label>
                  </th>
                  <td>
                    {% if form.new_password1.errors %}
                      <div class="form-error">
                        {% firstof form.new_password1.errors %}
                      </div>
                    {% endif %}
                    {{ form.new_password1 }}
                  </td>
                </tr>

                <tr>
                  <th>
                    <label for="id_new_password2">{% trans "Confirm" %}</label>
                  </th>
                  <td>
                    {% if form.new_password2.errors %}
                      <div class="form-error">
                        {% firstof form.new_password2.errors %}
                      </div>
                    {% endif %}
                    {{ form.new_password2 }}
                  </td>
                </tr>
              {% endif %}
            </table>
            {% if validlink %}
              <div>
                <input class="btn btn-primary" type="submit" value="{% block password_submit %}{% trans "Change my password" %}{% endblock %}">
                <a href="{% url "landing:landing_page" %}" type="submit" class="btn btn-cancel">{% trans "Cancel" %}</a>
              </div>
            {% endif %}
          </form>
          {% include "landing/_password_note.html" %}
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->
  </div>
  <!-- END .page -->
{% endblock %}

seed/landing/templates/landing/signup.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}


{% block js %}{{ block.super }}
  <script type="text/javascript">

    $(document).ready(function() {
      $('#id_new_password1').focus();
      $('#id_new_password1').attr('placeholder', '{% trans "Password" %}');
      $('#id_new_password2').attr('placeholder', '{% trans "Password again" %}');

    });

  </script>
{% endblock %}


{% block content %}

  <div class="page login">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}
      <!-- END .section_marketing -->
      <div class="section_forms">
        <div class="form_title">
          <h2>{% trans "Create Your Account" %}</h2>

          <form id="AuthNewPassword" class="signup_form" action="" method="post">
            {% csrf_token %}
            <table class="signup_table">
              <tr>
                {% if validlink %}
                  <td>
                    <p>{% block password_set_instructions %}{% trans "To set up your account, enter your password twice in the form below." %}{% endblock %}</p>
                  </td>
                {% else %}
                  <td>
                    <p>{% trans "The invite link was invalid, possibly because it has already been used.  Please request a new invitation." %}</p>
                  </td>
                {% endif %}
              </tr>

              {% if validlink %}
                <tr>
                  <th>
                    <label for="id_new_password1">{% trans "New password" %}</label>
                  </th>
                  <td>
                    {% if form.new_password1.errors %}
                      <div class="form-error">
                        {% firstof form.new_password1.errors %}
                      </div>
                    {% endif %}
                    {{ form.new_password1 }}
                  </td>
                </tr>

                <tr>
                  <th>
                    <label for="id_new_password2">{% trans "Confirm" %}</label>
                  </th>
                  <td>
                    {% if form.new_password2.errors %}
                      <div class="form-error">
                        {% firstof form.new_password2.errors %}
                      </div>
                    {% endif %}
                    {{ form.new_password2 }}
                  </td>
                </tr>
              {% endif %}
            </table>
            {% if validlink %}
              <div>
                <input class="btn btn-primary" type="submit" value="{% block password_submit %}{% trans "Create my account" %}{% endblock %}">
                <a href="{% url "landing:landing_page" %}" type="submit" class="btn btn-cancel">{% trans "Cancel" %}</a>
              </div>
            {% endif %}
          </form>
          {% include "landing/_password_note.html" %}
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->
  </div>
  <!-- END .page -->
{% endblock %}

seed/landing/templates/landing/thank_you.html
{% extends "landing/base.html" %}{% load compress %}{% load i18n %}

{% block content %}
  <div class="page">
    <div class="page_section">
      {% include "landing/_marketing_bullets.html" %}
      <!-- END .section_marketing -->
      <div class="section_forms">
        <div class="signup_form">
          <div class="form_title">
            <h2>{% trans "Thank you!" %}</h2>
          </div>
          <div class="thank_you">
            <div class="thank_you_text">{% trans "Thank you for your interest in joining the Buildings Performance Database. Our site is in beta and your request is being reviewed for access." %}</div>
            <a href="{% url "landing:landing_page" %}" type="submit" class="btn">{% trans "Back" %}</a>
          </div>
        </div>
      </div>
      <!-- END .section_forms -->
    </div>
    <!-- END .page_section .content -->
  </div>
  <!-- END .page -->
{% endblock %}