config/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from config.views import robots_txt
from seed.api.base.urls import urlpatterns as api
from seed.landing.views import (
    password_reset_complete,
    password_reset_confirm,
    password_reset_done
)
from seed.views.main import angular_js_tests, health_check, version

schema_view = get_schema_view(
    openapi.Info(
        title="SEED API",
        default_version='v3',
        description="SEED Platform API Documentation",
        # terms_of_service="https://www.google.com/policies/terms/",
        # contact=openapi.Contact(email="contact@snippets.local"),
        # license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=(permissions.AllowAny,),
)


def trigger_error(request):
    """Endpoint for testing sentry with a divide by zero"""
    1 / 0


urlpatterns = [
    re_path(r'^accounts/password/reset/done/$', password_reset_done, name='password_reset_done'),
    re_path(
        r'^accounts/password/reset/complete/$',
        password_reset_complete,
        name='password_reset_complete',
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        password_reset_confirm,
        name='password_reset_confirm'
    ),

    # Application
    re_path(r'^', include(('seed.landing.urls', "seed.landing"), namespace="landing")),
    re_path(r'^app/', include(('seed.urls', "seed"), namespace="seed")),
    re_path(r'^documentation/', include(('seed.docs.urls', 'seed.docs'), namespace='docs')),

    # root configuration items
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^robots\.txt', robots_txt, name='robots_txt'),

    # API
    re_path(r'^api/health_check/$', health_check, name='health_check'),
    re_path(r'^api/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^api/version/$', version, name='version'),
    re_path(r'^api/', include((api, "seed"), namespace='api')),
    re_path(r'^oauth/', include(('oauth2_jwt_provider.urls', 'oauth2_jwt_provider'), namespace='oauth2_provider')),

    # test sentry error
    path('sentry-debug/', trigger_error)
]

handler404 = 'seed.views.main.error404'
handler410 = 'seed.views.main.error410'
handler500 = 'seed.views.main.error500'


if settings.DEBUG:
    from django.contrib import admin

    admin.autodiscover()
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # test URLs
        re_path(r'^angular_js_tests/$', angular_js_tests, name='angular_js_tests'),

        # admin
        re_path(r'^admin/', admin.site.urls),
    ]

seed/api/v3/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.urls import include, re_path
from rest_framework import routers
from rest_framework_nested import routers as nested_routers

from seed.views.main import celery_queue
from seed.views.v3.analyses import AnalysisViewSet
from seed.views.v3.analysis_messages import AnalysisMessageViewSet
from seed.views.v3.analysis_views import AnalysisPropertyViewViewSet
from seed.views.v3.audit_template import AuditTemplateViewSet
from seed.views.v3.building_files import BuildingFileViewSet
from seed.views.v3.column_list_profiles import ColumnListProfileViewSet
from seed.views.v3.column_mapping_profiles import ColumnMappingProfileViewSet
from seed.views.v3.columns import ColumnViewSet
from seed.views.v3.compliance_metrics import ComplianceMetricViewSet
from seed.views.v3.cycles import CycleViewSet
from seed.views.v3.data_logger import DataLoggerViewSet
from seed.views.v3.data_quality_check_rules import DataQualityCheckRuleViewSet
from seed.views.v3.data_quality_checks import DataQualityCheckViewSet
from seed.views.v3.data_views import DataViewViewSet
from seed.views.v3.datasets import DatasetViewSet
from seed.views.v3.derived_columns import DerivedColumnViewSet
from seed.views.v3.eeej import EEEJViewSet
from seed.views.v3.events import EventViewSet
from seed.views.v3.filter_group import FilterGroupViewSet
from seed.views.v3.gbr_properties import GBRPropertyViewSet
from seed.views.v3.geocode import GeocodeViewSet
from seed.views.v3.green_assessment_properties import (
    GreenAssessmentPropertyViewSet
)
from seed.views.v3.green_assessment_urls import GreenAssessmentURLViewSet
from seed.views.v3.green_assessments import GreenAssessmentViewSet
from seed.views.v3.import_files import ImportFileViewSet
from seed.views.v3.label_inventories import LabelInventoryViewSet
from seed.views.v3.labels import LabelViewSet
from seed.views.v3.measures import MeasureViewSet
from seed.views.v3.media import MediaViewSet
from seed.views.v3.meter_readings import MeterReadingViewSet
from seed.views.v3.meters import MeterViewSet
from seed.views.v3.notes import NoteViewSet
from seed.views.v3.organization_users import OrganizationUserViewSet
from seed.views.v3.organizations import OrganizationViewSet
from seed.views.v3.portfolio_manager import PortfolioManagerViewSet
from seed.views.v3.postoffice import PostOfficeEmailViewSet, PostOfficeViewSet
from seed.views.v3.progress import ProgressViewSet
from seed.views.v3.properties import PropertyViewSet
from seed.views.v3.property_measures import PropertyMeasureViewSet
from seed.views.v3.property_scenarios import PropertyScenarioViewSet
from seed.views.v3.property_views import PropertyViewViewSet
from seed.views.v3.salesforce_configs import SalesforceConfigViewSet
from seed.views.v3.salesforce_mappings import SalesforceMappingViewSet
from seed.views.v3.tax_lot_properties import TaxLotPropertyViewSet
from seed.views.v3.taxlot_views import TaxlotViewViewSet
from seed.views.v3.taxlots import TaxlotViewSet
from seed.views.v3.ubid import UbidViewSet
from seed.views.v3.uploads import UploadViewSet
from seed.views.v3.users import UserViewSet

api_v3_router = routers.DefaultRouter()
api_v3_router.register(r'analyses', AnalysisViewSet, basename='analyses')
api_v3_router.register(r'audit_template', AuditTemplateViewSet, basename='audit_template')
api_v3_router.register(r'building_files', BuildingFileViewSet, basename='building_files')
api_v3_router.register(r'column_list_profiles', ColumnListProfileViewSet, basename='column_list_profiles')
api_v3_router.register(r'column_mapping_profiles', ColumnMappingProfileViewSet, basename='column_mapping_profiles')
api_v3_router.register(r'columns', ColumnViewSet, basename='columns')
api_v3_router.register(r'compliance_metrics', ComplianceMetricViewSet, basename='compliance_metrics')
api_v3_router.register(r'cycles', CycleViewSet, basename='cycles')
api_v3_router.register(r'data_loggers', DataLoggerViewSet, basename='data_logger')
api_v3_router.register(r'data_quality_checks', DataQualityCheckViewSet, basename='data_quality_checks')
api_v3_router.register(r'data_views', DataViewViewSet, basename='data_views')
api_v3_router.register(r'datasets', DatasetViewSet, basename='datasets')
api_v3_router.register(r'derived_columns', DerivedColumnViewSet, basename='derived_columns')
api_v3_router.register(r'eeej', EEEJViewSet, basename='eeej')
api_v3_router.register(r'filter_groups', FilterGroupViewSet, basename='filter_groups')
api_v3_router.register(r'gbr_properties', GBRPropertyViewSet, basename='properties')
api_v3_router.register(r'geocode', GeocodeViewSet, basename='geocode')
api_v3_router.register(r'green_assessment_properties', GreenAssessmentPropertyViewSet, basename='green_assessment_properties')
api_v3_router.register(r'green_assessment_urls', GreenAssessmentURLViewSet, basename='green_assessment_urls')
api_v3_router.register(r'green_assessments', GreenAssessmentViewSet, basename='green_assessments')
api_v3_router.register(r'import_files', ImportFileViewSet, basename='import_files')
api_v3_router.register(r'labels', LabelViewSet, basename='labels')
api_v3_router.register(r'measures', MeasureViewSet, basename='measures')
api_v3_router.register(r'organizations', OrganizationViewSet, basename='organizations')
api_v3_router.register(r'portfolio_manager', PortfolioManagerViewSet, basename='portfolio_manager')
api_v3_router.register(r'postoffice', PostOfficeViewSet, basename='postoffice')
api_v3_router.register(r'postoffice_email', PostOfficeEmailViewSet, basename='postoffice_email')
api_v3_router.register(r'progress', ProgressViewSet, basename='progress')
api_v3_router.register(r'properties', PropertyViewSet, basename='properties')
api_v3_router.register(r'property_views', PropertyViewViewSet, basename='property_views')
api_v3_router.register(r'salesforce_configs', SalesforceConfigViewSet, basename='salesforce_configs')
api_v3_router.register(r'salesforce_mappings', SalesforceMappingViewSet, basename='salesforce_mappings')
api_v3_router.register(r'tax_lot_properties', TaxLotPropertyViewSet, basename='tax_lot_properties')
api_v3_router.register(r'taxlot_views', TaxlotViewViewSet, basename='taxlot_views')
api_v3_router.register(r'taxlots', TaxlotViewSet, basename='taxlots')
api_v3_router.register(r'ubid', UbidViewSet, basename='ubid')
api_v3_router.register(r'upload', UploadViewSet, basename='upload')
api_v3_router.register(r'users', UserViewSet, basename='user')

data_quality_checks_router = nested_routers.NestedSimpleRouter(api_v3_router, r'data_quality_checks', lookup='nested')
data_quality_checks_router.register(r'rules', DataQualityCheckRuleViewSet, basename='data_quality_check-rules')

organizations_router = nested_routers.NestedSimpleRouter(api_v3_router, r'organizations', lookup='organization')
organizations_router.register(r'users', OrganizationUserViewSet, basename='organization-users')

analysis_views_router = nested_routers.NestedSimpleRouter(api_v3_router, r'analyses', lookup='analysis')
analysis_views_router.register(r'views', AnalysisPropertyViewViewSet, basename='analysis-views')

analysis_messages_router = nested_routers.NestedSimpleRouter(api_v3_router, r'analyses', lookup='analysis')
analysis_messages_router.register(r'messages', AnalysisMessageViewSet, basename='analysis-messages')

analysis_view_messages_router = nested_routers.NestedSimpleRouter(analysis_views_router, r'views', lookup='views')
analysis_view_messages_router.register(r'views_messages', AnalysisMessageViewSet, basename='analysis-messages')

properties_router = nested_routers.NestedSimpleRouter(api_v3_router, r'properties', lookup='property')
properties_router.register(r'meters', MeterViewSet, basename='property-meters')
properties_router.register(r'notes', NoteViewSet, basename='property-notes')
properties_router.register(r'scenarios', PropertyScenarioViewSet, basename='property-scenarios')
properties_router.register(r'events', EventViewSet, basename='property-events')

# This is a third level router, so we need to register it with the second level router
meters_router = nested_routers.NestedSimpleRouter(properties_router, r'meters', lookup='meter')
meters_router.register(r'readings', MeterReadingViewSet, basename='property-meter-readings')


property_measures_router = nested_routers.NestedSimpleRouter(properties_router, r'scenarios', lookup='scenario')
property_measures_router.register(r'measures', PropertyMeasureViewSet, basename='property-measures')

taxlots_router = nested_routers.NestedSimpleRouter(api_v3_router, r'taxlots', lookup='taxlot')
taxlots_router.register(r'notes', NoteViewSet, basename='taxlot-notes')


urlpatterns = [
    re_path(r'^', include(api_v3_router.urls)),
    re_path(r'^', include(data_quality_checks_router.urls)),
    re_path(
        r'^labels_property/$',
        LabelInventoryViewSet.as_view(),
        {'inventory_type': 'property'},
    ),
    re_path(
        r'^labels_taxlot/$',
        LabelInventoryViewSet.as_view(),
        {'inventory_type': 'taxlot'},
    ),
    re_path(r'^', include(organizations_router.urls)),
    re_path(r'^', include(analysis_views_router.urls)),
    re_path(r'^', include(analysis_messages_router.urls)),
    re_path(r'^', include(analysis_view_messages_router.urls)),
    re_path(r'^', include(properties_router.urls)),
    re_path(r'^', include(meters_router.urls)),
    re_path(r'^', include(property_measures_router.urls)),
    re_path(r'^', include(taxlots_router.urls)),
    re_path(r'^celery_queue/$', celery_queue, name='celery_queue'),
    re_path(r'media/(?P<filepath>.*)$', MediaViewSet.as_view()),
]

seed/docs/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.urls import re_path

from seed.docs.views import faq_page

urlpatterns = [
    re_path(r'^$', faq_page, name='documentation'),
]

seed/landing/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.conf import settings
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordChangeView,
    logout_then_login
)
from django.urls import re_path

from seed.landing.views import (
    account_activation_sent,
    activate,
    create_account,
    landing_page,
    password_reset,
    password_reset_complete,
    password_reset_done,
    signup
)

urlpatterns = [
    re_path(r'^$', landing_page, name='landing_page'),
    re_path(r'^accounts/login/$', landing_page, name='login'),
    re_path(
        r'^accounts/logout/$',
        logout_then_login,
        name='logout'
    ),
    re_path(r'^accounts/password/reset/$', password_reset, name='password_reset'),
    re_path(r'^accounts/password/reset/done/$', password_reset_done, name='password_reset_done'),
    re_path(
        r'^accounts/password/reset/complete/$',
        password_reset_complete,
        name='password_reset_complete',
    ),
    re_path(
        (
            r'^accounts/setup/(?P<uidb64>[0-9A-Za-z_\-]+)/'
            '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$'
        ),
        signup,
        name='signup'
    ),
    re_path(
        r'^password_change/$',
        PasswordChangeView.as_view(),
        {'template_name': 'landing/password_change_form.html'},
        name="password_change"
    ),
    re_path(
        r'^password_change/done/$',
        PasswordChangeDoneView.as_view(),
        {'template_name': 'landing/password_change_done.html'}
    ),
]

if settings.INCLUDE_ACCT_REG:
    urlpatterns += [
        re_path(r'^accounts/create/$', create_account, name='create_account'),
        re_path(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),
        re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate')
    ]

seed/urls.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.urls import re_path

from seed.views.main import home

urlpatterns = [
    re_path(r'^$', home, name='home'),
]

seed/models/analysis_input_files.py
# !/usr/bin/env python
# encoding: utf-8
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from django.db import models

from seed.models import Analysis


def analysis_input_path(instance, filename):
    """Returns the path to where an AnalysisInputFile's file is stored.
    Ie only modify this function if you want to change that location.

    :param instance: AnalysisFile
    :param filename: str
    :returns: str
    """
    if instance.analysis_id is None:
        raise Exception('Unable to save analysis input file. Linked Analysis must have an ID (i.e., already saved in db)')
    return f'analysis_input_files/{instance.analysis_id}/{filename}'


class AnalysisInputFile(models.Model):
    """
    The AnalysisInputFile is a file used as input for an analysis.

    For example, if running an analysis on multiple properties, it might be a
    CSV containing data collected from each property.
    """
    BUILDINGSYNC = 1

    CONTENT_TYPES = (
        (BUILDINGSYNC, 'BuildingSync'),
    )

    file = models.FileField(upload_to=analysis_input_path, max_length=500)
    content_type = models.IntegerField(choices=CONTENT_TYPES)
    analysis = models.ForeignKey(Analysis, related_name='input_files', on_delete=models.CASCADE)

seed/models/auditlog.py
"""
SEED Platform (TM), Copyright (c) Alliance for Sustainable Energy, LLC, and other contributors.
See also https://github.com/seed-platform/seed/main/LICENSE.md
"""
from __future__ import unicode_literals

AUDIT_IMPORT = 0
AUDIT_USER_EDIT = 1
AUDIT_USER_CREATE = 2

DATA_UPDATE_TYPE = (
    (AUDIT_IMPORT, "ImportFile"),
    (AUDIT_USER_EDIT, "UserEdit"),
    (AUDIT_USER_CREATE, "UserCreate")
)

seed/templates/seed/_footer.html
<div class="footer">
  <table>
    <tr>
      <td>{# Optional left side logo #}</td>
      <td>{# Optional center logo #}</td>
      <td>{# Optional right side logo #}</td>
    </tr>
  </table>
</div>

seed/templates/seed/_js_urls.html
<script type="text/javascript">
  // config URLs
  window.BE = window.BE || {};
  // new URLs
  window.BE.app_urls = {
    seed: { home: '/app/' },
    audit_logs: {
      create_note: '/audit_logs/create_note/',
      update_note: '/audit_logs/update_note/',
      get_building_logs: '/audit_logs/get_building_logs/',
    },
  };

  // old URLs
  window.BE.urls = window.BE.urls || {};
  // static URLs
  window.BE.urls.STATIC_URL = '{{ STATIC_URL }}';

  window.BE.urls.seed_home = '{% url "seed:home" %}';
</script>

seed/templates/seed/_sidebar.html
{% load compress %}{# requires menu_controller angularjs controller and menu_controller.js #}
<div ng-class="{expanded: expanded_controller, collapsed: collapsed_controller, sidebar: true, hide_transition:is_initial_state}">
    <div class="menu">
        <a id="sidebar-menu" class="item" ng-click="toggle_menu()">
            <div class="icon">
                <i class="fa-solid fa-lg fa-bars"></i>
                <span ng-switch="expanded_controller" class="toggle">
                  <i ng-switch-when="true" id="sidebar-menu-close" class="fa-solid fa-chevron-left fa-sm"></i>
                  <i ng-switch-when="false" id="sidebar-menu-open" class="fa-solid fa-chevron-right fa-sm"></i>
                </span>
            </div>
        </a>
        <a id="sidebar-profile" class="item" ng-class="{active: is_active('/profile'), 'disabled-item': !logged_in}" href="{% url "seed:home" %}#/profile">
            <div class="icon"><i class="fa-solid fa-lg fa-gear"></i></div>
            <div class="item_name">{$ username $}</div>
        </a>
        <div class="divider"></div>
        <a id="sidebar-inventory" ng-class="{item: true, active: is_active('/properties') || is_active('/taxlots'), 'disabled-item': !logged_in}" href="{% url "seed:home" %}#/properties">
            <div class="icon"><i class="fa-solid fa-lg fa-building"></i></div>
            <div class="item_name" translate>Inventory</div>
        </a>
        <a id="sidebar-data" ng-class="{item: true, active: is_active('/data'), 'disabled-item': !logged_in}" title="{$:: 'Data' | translate $}" href="{% url "seed:home" %}#/data" ng-show="menu.user.organization.user_role !== 'viewer'">
            <div class="icon"><i class="fa-solid fa-lg fa-sitemap"></i></div>
            <div class="item_name" translate>Data</div>
            <div ng-show="logged_in" class="badge badge_menu">{$ datasets_count | number:0 $}</div>
        </a>
        <a id="sidebar-accounts" ng-class="{item: true, active: is_active('/accounts'), 'disabled-item': !logged_in}" title="{$:: 'Organizations' | translate $}" href="{% url "seed:home" %}#/accounts">
            <div class="icon"><i class="fa-solid fa-lg fa-users"></i></div>
            <div class="item_name" translate>Organizations</div>
            <div ng-show="logged_in" class="badge badge_menu">{$ organizations_count | number:0 $}</div>
        </a>
        <a id="sidebar-accounts" ng-class="{item: true, active: is_active('/insights'), 'disabled-item': !logged_in}" title="{$:: 'Insights' | translate $}" href="{% url "seed:home" %}#/insights">
            <div class="icon"><i class="fa-solid fa-lg fa-gauge-high"></i></div>
            <div class="item_name" translate>Insights</div>
        </a>

        <a id="sidebar-accounts" ng-class="{item: true, active: is_active('/analyses'), 'disabled-item': !logged_in}" title="{$:: 'Analyses' | translate $}" href="{% url "seed:home" %}#/analyses">
            <div class="icon"><i class="fa-solid fa-lg fa-bar-chart"></i></div>
            <div class="item_name" translate>Analyses</div>
        </a>

        <div class="divider"></div>

        <a id="sidebar-api" ng-class="{item: true, active: is_active('/api/swagger'), 'disabled-item': !logged_in}" title="{$:: 'API Documentation' | translate $}" href="{% url "seed:home" %}#/api/swagger">
            <div class="icon"><i class="fa-solid fa-lg fa-code"></i></div>
            <div class="item_name" translate>API Documentation</div>
        </a>
        <a id="sidebar-contact" ng-class="{item: true, active: is_active('/contact'), 'disabled-item': !logged_in}" title="{$:: 'Contact' | translate $}" href="{% url "seed:home" %}#/contact">
            <div class="icon"><i class="fa-solid fa-lg fa-question-circle"></i></div>
            <div class="item_name" translate>Contact</div>
        </a>
        <a id="sidebar-about" ng-class="{item: true, active: is_active('/about'), 'disabled-item': !logged_in}" title="{$:: 'About' | translate $}" href="{% url "seed:home" %}#/about">
            <div class="icon"><i class="fa-solid fa-lg fa-info-circle"></i></div>
            <div class="item_name" translate>About</div>
        </a>
        <a id="sidebar-docs" ng-class="{item: true, active: is_active('/documentation/', true)}" title="{$:: 'Documentation' | translate $}" href="{% url "docs:documentation" %}#/">
            <div class="icon"><i class="fa-solid fa-lg fa-book"></i></div>
            <div class="item_name" translate>Documentation</div>
        </a>
        <a id="sidebar-logout" class="item" ng-class="{'disabled-item': !logged_in}" title="{$:: 'Logout' | translate $}" href="{% url "landing:logout" %}">
            <div class="icon"><i class="fa-solid fa-lg fa-sign-out"></i></div>
            <div class="item_name" translate>Logout</div>
        </a>
    </div>
</div>

seed/templates/seed/account_create_email.html
{% load i18n %}{% autoescape off %}
  {% blocktrans %}Hello {{ first_name }}, {% endblocktrans %}

  {% trans "You're receiving this e-mail because you've been registered for a SEED account." %}

  {% blocktrans %}SEED is easy, flexible, and cost effective software designed to help organizations clean, manage and share information about large portfolios of buildings. SEED is a free, open
    source web application that you can use privately.  While SEED was originally designed to help cities and States implement benchmarking programs for public or private buildings, it has the
    potential to be useful for many other activities by public entities, efficiency programs and private companies.{% endblocktrans %}

  {% trans "Please go to the following page and setup your account:" %}
  {% block reset_link %}
    {{ protocol }}://{{ domain }}{{ signup_url }}
  {% endblock %}

  {% blocktrans %}The SEED Team{% endblocktrans %}

{% endautoescape %}

seed/templates/seed/account_org_added.html
{% load i18n %}{% autoescape off %}
  {% blocktrans %}Hello {{ first_name }}, {% endblocktrans %}

  {% blocktrans %}You are receiving this e-mail because you have been added to the '{{ new_org }}' organization by '{{ requested_by }}'. Please disregard this message if you are not expecting access
    to SEED.{% endblocktrans %}

  {% blocktrans %}You can view your new organization by logging into the SEED instance here:{% endblocktrans %}
  {{ protocol }}://{{ domain }}

  {% blocktrans %}The SEED Team{% endblocktrans %}

{% endautoescape %}

seed/templates/seed/index.html
{% extends "seed/base.html" %}{% load compress %}

{% block js %}{{ block.super }}
{% endblock %}

{% block content %}
<div ng-controller="menu_controller" class="ng-cloak">
  {% include "seed/_sidebar.html" %}

  <div class="display">
    <div ng-class="{narrow: narrow_controller, wide: wide_controller, content: true, hide_transition:is_initial_state}">
      {% include "seed/_header.html" %}

      <div class="page">
        <div class="alert warning" ng-show="route_load_error">
          <div class="alert alert-danger">
            <button type="button" class="close" ng-click="hide_load_error()">&times;</button>
            {$ load_error_message || ('There was an error loading the page' | translate) $}
          </div>
        </div>
        <div ui-view class="ui-view-container"></div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

seed/templates/seed/salesforce_update_errors.html
{% load i18n %}{% autoescape off %}
  {% blocktrans %}Hello, {% endblocktrans %}

  {% blocktrans %}You're receiving this message because your e-mail is registered as the 'logging email' for Salesforce updates in the SEED {{ organization_name }} organization. {% endblocktrans %}

  {% blocktrans %}Errors were encountered while running the automatic Salesforce update process:{% endblocktrans %}

  {% blocktrans %}{{ errors }}{% endblocktrans %}


  {% blocktrans %}The SEED Team{% endblocktrans %}

{% endautoescape %}